name: Babelfish for PostgreSQL Website Bug Report
description: File a bug report for Babelfish Website
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report.
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: Describe the expected behavior of the website. 
      placeholder: Tell us what you see.
      value: "Describe the expected behavior of the website."
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://aws.github.io/code-of-conduct-faq).
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true