name: Babelfish for PostgreSQL Website Feature Request Form
description: Propose an enhancement for the Babelfish for PostgreSQL Website
title: "[Enhancement]: "
labels: ["enhancement", "untriaged"]
assignees:
  - 3manuek
  - gopinathpai
  - xaviersierra
  - nasbyj
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this feature request.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Please provide an email address where we can contact you for more information.
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-intends
    attributes:
      label: Describe the enhancement, and how the change will improve the website.
      description: Provide as much detailed information as you can about the website improvement.
      placeholder: Tell us what you have in mind!
      value: "This is my feature request!"
    validations:
      required: true
  - type: textarea
    id: brief-desc-implementation
    attributes:
      label: Share implementation details for the website enhancement.
      description: Share detailed information about the implementation.
    validations:
      required: false 
  - type: textarea
    id: docs
    attributes:
      label: Relevant documentation
      description: Please attach any documentation relevant to the enhancement.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://aws.github.io/code-of-conduct-faq).
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true